// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServerMvcAppSportDb.Data;

#nullable disable

namespace SqlServerMvcAppSportDb.Migrations
{
    [DbContext(typeof(SportDbContext))]
    [Migration("20250410152531_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlServerMvcAppSportDb.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Ball",
                            Name = "Football",
                            Price = 29.99m
                        },
                        new
                        {
                            ID = 2,
                            Category = "Ball",
                            Name = "Basketball",
                            Price = 34.99m
                        },
                        new
                        {
                            ID = 3,
                            Category = "Footwear",
                            Name = "Running Shoes",
                            Price = 89.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
