// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcAppAws_MartinSanchez.Data;

#nullable disable

namespace MvcAppAws_MartinSanchez.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250418053536_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcAppAws_MartinSanchez.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaAsignada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carrera = "Ingeniería Informática",
                            EmpresaAsignada = "TechSolutions",
                            Estado = "Activo",
                            FechaFin = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "001-INF",
                            NombreCompleto = "Ana Martínez López"
                        },
                        new
                        {
                            Id = 2,
                            Carrera = "Matemáticas",
                            EmpresaAsignada = "DataAnalytics MX",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "002-MAT",
                            NombreCompleto = "Carlos Ramírez Soto"
                        },
                        new
                        {
                            Id = 3,
                            Carrera = "Administración",
                            EmpresaAsignada = "Grupo Empresarial del Norte",
                            Estado = "Activo",
                            FechaFin = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "003-ADM",
                            NombreCompleto = "Lucía Herrera Gómez"
                        },
                        new
                        {
                            Id = 4,
                            Carrera = "Ingeniería Industrial",
                            EmpresaAsignada = "Industrias Alfa",
                            Estado = "En espera",
                            FechaFin = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "004-IND",
                            NombreCompleto = "Miguel Torres Díaz"
                        },
                        new
                        {
                            Id = 5,
                            Carrera = "Derecho",
                            EmpresaAsignada = "Bufete Legal MX",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "005-DER",
                            NombreCompleto = "Sofía Ruiz Vega"
                        },
                        new
                        {
                            Id = 6,
                            Carrera = "Matemáticas",
                            EmpresaAsignada = "Cálculo Avanzado S.A.",
                            Estado = "Activo",
                            FechaFin = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "006-MAT",
                            NombreCompleto = "Diego Mendoza Pérez"
                        },
                        new
                        {
                            Id = 7,
                            Carrera = "Psicología",
                            EmpresaAsignada = "Centro Psicológico Integral",
                            Estado = "Activo",
                            FechaFin = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "007-PSI",
                            NombreCompleto = "Valeria Jiménez Castro"
                        },
                        new
                        {
                            Id = 8,
                            Carrera = "Arquitectura",
                            EmpresaAsignada = "Diseño Urbano MX",
                            Estado = "En espera",
                            FechaFin = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "008-ARQ",
                            NombreCompleto = "Fernando Navarro Gil"
                        },
                        new
                        {
                            Id = 9,
                            Carrera = "Ingeniería Informática",
                            EmpresaAsignada = "AppDev Studio",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "009-INF",
                            NombreCompleto = "Mariana Salas Pineda"
                        },
                        new
                        {
                            Id = 10,
                            Carrera = "Administración",
                            EmpresaAsignada = "Consultores Estratégicos",
                            Estado = "Activo",
                            FechaFin = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "010-ADM",
                            NombreCompleto = "José Luis Carrillo Ramos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
