// <auto-generated />
using AngularApp1.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularApp1.Server.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AngularApp1.Server.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan.perez@example.com",
                            Name = "Juan Pérez",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.lopez@example.com",
                            Name = "María López",
                            Phone = "234-567-8901"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.gomez@example.com",
                            Name = "Carlos Gómez",
                            Phone = "345-678-9012"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.martinez@example.com",
                            Name = "Ana Martínez",
                            Phone = "456-789-0123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
